namespace TehGM.Randominator.Generators.MobileGameName
{
    public class MobileGameNameOptions
    {
        public ICollection<string> MiddleWordSet { get; set; } = new string[] { "of" };

        public ICollection<string> LeadingWordSet { get; set; } = new string[] 
        { 
            "Game"
        };
        public ICollection<string> TrailingWordSet { get; set; } = new string[] { };
        public ICollection<string> SharedWordSet { get; set; } = new string[] 
        {
            "Age",
            "Clash",
            "Clans",
            "Clan",
            "Empire",
            "Empires",
            "Nation",
            "Nations",
            "Consent",
            "Conquest",
            "Conquests",
            "Rise",
            "Myth",
            "Myths",
            "Legend",
            "Legends",
            "End",
            "Ends",
            "Immortal",
            "Immortals",
            "Evolution",
            "King",
            "Kings",
            "Lord",
            "Lords",
            "War",
            "Wars",
            "Return",
            "Idle",
            "Tycoon",
            "Saga",
            "Order",
            "Forge",
            "Mobile",
            "Merge",
            "Gold",
            "Infinite",
            "Royale",
            "Survival",
            "Hero",
            "Heroes",
            "League",
            "Leagues",
            "Era",
            "Chaos",
            "Fantasy",
            "Return",
            "Fishing",
            "Candy",
            "Dragon",
            "Dragons",
            "Knight",
            "Knights",
            "Racing",
            "Fever",
            "Sniper",
            "Snipers",
            "Idle Defense",
            "Defense",
            "Crafting",
            "Epic Idle",
            "Super Idle",
            "Epic Crafting",
            "Super Crafting",
            "Dream",
            "Dreams",
            "Dream League",
            "Impact",
            "Legion",
            "Legions",
            "Art",
            "Garden",
            "Gardens",
            "Origin",
            "Origins"
        };
    }
}
